### ISSUE TITLE
SPADES alternative

### ISSUE THREAD

**Issue by PedroBarbosa** [mdcao/npScarf#10]
Hello,

I have some previously generated draft using other assembly pipeline, which doesn't contain the required information in the FASTA headers. 

I'd like to ask if there is any other way to generate such headers, because I can't go back and redo assembly from scratch. 

Thanks in advance,
Pedro

**Comment by hsnguyen** [comment]
Hi Pedro,
SPAdes header is generated during its process, containing information about coverage and length of each sequences. While the length info can be generated easily, coverage of a contig (rooted from De brujin graph) unfortunately cannot be.
However, npScarf could run without the SPAdes-like header because it's originally designed to work with every draft assemblies; but of course its accuracy would be affected by the lack of such information.
Good luck with your assembly!

**Comment by PedroBarbosa** [comment]
Ok, thank you @hsnguyen , I'll give it a try anyway!

Best,
Pedro
