### ISSUE TITLE
npScarf crashes

### ISSUE THREAD

**Issue by fg6** [mdcao/npScarf#5]
Hi,
I am running @ npScarf on a few nanopore and PacBio datasets and it is generally working fine. 
On a PacBio dataset though it crashes with error:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: -1, Size: 1
    at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
    at java.util.LinkedList.remove(LinkedList.java:525)
    at japsa.bio.hts.scaffold.ScaffoldGraph.joinScaffold(ScaffoldGraph.java:494)
    at japsa.bio.hts.scaffold.ScaffoldGraphDFS.walk2(ScaffoldGraphDFS.java:309)
    at japsa.bio.hts.scaffold.ScaffoldGraphDFS.connectBridges(ScaffoldGraphDFS.java:99)
    at japsa.tools.bio.np.GapCloserCmd.main(GapCloserCmd.java:139)
The full report is in the attached file. It seems the problem occurs when it tries to connect contigs
122, 147 and 116 to Scaffold 79, and indeed if I take out 122 or 116 from the initial fasta everything 
works fine, but I couldn't figure out where the problem is, can you help me figure out what is wrong or what should I look at to start with? 

The pipeline I am running is:
jsa.seq.sort -r -n --input  spades.fasta --output sort_spades.fasta 
bwa index sort_spades.fasta
bwa mem -t 10 -k11 -W20 -r10 -A1 -B1 -O1 -E1 -L0 -a -Y sort_spades.fasta pacbio.fastq  | jsa.np.gapcloser -b - -seq sort_spades.fasta  --verbose  --output=npScarf.fasta

where spades.fasta is my initial assembly from spades, and pacbio.fastq the fastq with the pacbio reads,
and I am using the japsa package: Version 1.6-01c, Built on Thu Jun 23 10:10:20 BST 2016 with javac 1.7.0_80.
Please let me know if you need additional info.

Thank you a lot!
Fran

[output.txt](https://github.com/mdcao/npScarf/files/470043/output.txt)

**Comment by hsnguyen** [comment]
Hi Fran,
Can you checkout for the newest version of npScarf (version 1.6-08a) from current japsa package and run again?
Other few suggestions:
1. For PacBio data, you might want to use another parameter set for `bwa mem` command to get better alignments (the one used in our pipeline is optimized for nanopore data).
2. Looking at your log file, the spades contigs seem unfamiliar to me. Usually their name are formatted like 

> NODE_?_length_?_cov_?_ID_?

 (? represent numbers). This is important since npScarf will use information about the length and coverage of a contig to predict its uniqueness. If the coverage figures are missing, the results could be inferior.
Happy assembly!

**Comment by fg6** [comment]
Hi! 
thanks for the quick reply! Yes you're right about the SPAdes assembly, I slightly changed it for other reasons and I missed npScarf needed the exact format from SPAdes.  Using directly contigs.fasta and the new japsa release everything works fine now!

Thank you!
Fran
